import '../globals.css'

import type { Metadata } from 'next'
import Providers from '@/components/layout/providers'

import { Poppins, Raleway } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

const raleway = Raleway({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Socifit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} flex overflow-y-hidden h-screen min-w-[650px]`}
      >
        <Providers>
          <main className="flex-1 flex h-full">
            <div className={`bg-primary flex-1 ${raleway.className} relative`}>
              <h2 className="text-white font-bold p-8">Constrular</h2>

              <div className="text-white absolute top-1/4 flex flex-col p-8 gap-4">
                <h1 className="max-w-[496px] text-2xl md:text-3xl lg:text-5xl">
                  Simplifique a Gestão do Seu Negócio
                </h1>
                <h2 className="font-normal max-w-96 text-lg sm:text-xl lg:text-2xl">
                  PDV, estoque, contas e relatórios em um só sistema fácil de
                  usar.
                </h2>
              </div>
            </div>
            <div className="h-screen flex-1">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
