version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pdv_db
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - "app-network"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
        interval: 5s
        timeout: 5s
        retries: 5
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:secret@db:5432/pdv_db
      - JWT_SECRET=secret
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - "app-network"
    command: sh -c "./start.sh"
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - db
    networks:
      - "app-network"

volumes:
  pgdata:

networks:
    app-network:
        driver: bridge