FROM node:20.18.1

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY start.sh ./start.sh
RUN chmod +x ./start.sh

RUN npm install

COPY . .

CMD ["./start.sh"]

EXPOSE 3001
EXPOSE 5555